version: '3'
services:
  first:
    image: 'tomcat:9'
    ports:
      - "8081:8080"
    volumes:
      - "/mnt/war:/usr/local/tomcat/webapps"
  second:
    image: 'tomcat:9'
    ports:
      - "8082:8080"
    volumes:
      - "/mnt/war:/usr/local/tomcat/webapps"


